

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/clientes/**
          filters:
            - StripPrefix=1


server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
