eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
    instance:
    preferIpAddress: true

spring:
  application:
    name: ms-customer
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres
  flyway:
    enabled: true
  jpa:
    hibernate:
    ddlAuto: update
    showSql: true
    properties:
      hibernate:
        formatSql: true
      dialect: org.hibernate.dialect.PostgreSQL81Dialect

server:
  port: 0

logging:
  level:
    org:
      springframework:
        web=DEBUG:
